on:
  push:
    branches:
      - master
name: release-please
jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:

      - uses: google-github-actions/release-please-action@v3
        id: release
        with:
          release-type: go
          package-name: release-please-action
          extra-files: core/lib/data/def.go

      - uses: actions/setup-go@v2
        with:
          go-version: '^1.18'

      - name: Create release archive
        if: ${{ steps.release.outputs.release_created }}
        run: |
          cd core || exit 1
          ls -lah
          bash ./emp3r0r --release || exit 2
          mv emp3r0r.tar.xz emp3r0r-v${{ steps.release.outputs.major }}.${{ steps.release.outputs.minor }}.${{ steps.release.patch }}.tar.xz || exit 3
          ls -lah
          curl -F emp3r0r-v${{ steps.release.outputs.major }}.${{ steps.release.outputs.minor }}.${{ steps.release.patch }}.tar.xz -X POST -H "Accept: application/x-tar" ${{ steps.release.outputs.upload_url }} || exit 4

